# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74799a3399d19762caa4f465c1061706159d7d5a372ee1590e06e040a7f589a36cd7c7c533a23f833f195b3bd98e2caa883045518b344149d60bfd336e1629f4

test:
  secret_key_base: 3d0f81307873d7a9a062833a321ce4a68e50cb30ed5f35cfc0ae33a581f81b4d6002180cdb095dcbc7122265943f1271a4af08f6bb7322a7421b4c5f80216e08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
